-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: localhost:8889
-- Generation Time: Jul 27, 2024 at 09:13 PM
-- Server version: 5.7.39
-- PHP Version: 7.4.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `projet2`
--

-- --------------------------------------------------------

--
-- Table structure for table `recettes`
--

CREATE TABLE `recettes` (
  `id` int(11) NOT NULL,
  `nom` text NOT NULL,
  `ingredients` text,
  `description` text,
  `categorie` int(11) NOT NULL,
  `image` text NOT NULL,
  `date_creation` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `owner_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `recettes`
--

INSERT INTO `recettes` (`id`, `nom`, `ingredients`, `description`, `categorie`, `image`, `date_creation`, `owner_id`) VALUES
(1, 'tarte', 'Pâte Sablée :\r\n\r\n250 g de farine\r\n140 g de beurre non salé (froid)\r\n100 g de sucre glace\r\n¼ cuillère à café de sel fin\r\n1 œuf\r\nZeste de citron\r\n\r\nCrème Pâtissière :\r\n\r\n500 g de lait entier\r\n4 jaunes d\'œufs\r\n1 œuf\r\n120 g de sucre en poudre\r\n40 g de fécule de maïs\r\n¼ cuillère à café de sel fin\r\n30 g de beurre non salé\r\n½ cuillère à café de pâte de vanille\r\n\r\nAssemblage :\r\n\r\n500 g de fraises fraîches\r\n2 cuillères à soupe de sucre en poudre', '\r\nPréparation de la pâte :\r\n\r\n1.Coupez le beurre en dés et placez-le au réfrigérateur.\r\n2.Tamisez la farine, le sucre glace et le sel dans un bol. Ajoutez le beurre froid et mélangez du bout des doigts jusqu\'à obtenir une texture sableuse.\r\n3.Ajoutez l\'œuf et le zeste de citron. Mélangez jusqu\'à formation d\'une pâte homogène. Enveloppez dans du film plastique et réfrigérez 20-30 minutes.\r\n4.Étalez la pâte entre deux feuilles de papier sulfurisé. Réfrigérez encore 20-30 minutes.\r\n5.Préchauffez le four à 160°C (325°F) avec ventilateur ou 175°C (350°F) sans ventilateur.\r\n6.Placez la pâte dans un moule à tarte beurré. Piquez la pâte avec une fourchette, recouvrez de papier sulfurisé et de poids de cuisson. Faites cuire à blanc 15 minutes, retirez le papier et les poids, puis continuez la cuisson 10-15 minutes jusqu\'à dorure. Laissez refroidir.\r\n\r\nPréparation de la crème pâtissière :\r\n\r\n1.Chauffez le lait jusqu\'à ébullition. Dans un bol, mélangez les jaunes d\'œufs, l\'œuf, la fécule de maïs, le sucre et le sel.\r\n2.Versez lentement ⅔ du lait chaud dans le mélange d\'œufs, en fouettant constamment. Remettez le tout dans la casserole avec le reste du lait et continuez à cuire en remuant jusqu\'à épaississement.\r\n3.Ajoutez la vanille et le beurre. Mélangez jusqu\'à obtention d\'une crème lisse. Passez au tamis dans la croûte de tarte refroidie. Couvrez de film plastique et laissez refroidir à température ambiante, puis réfrigérez.\r\n\r\nAssemblage :\r\n\r\n1.Lavez et équeutez les fraises. Coupez-les en deux ou en trois selon leur taille. Mélangez avec le sucre et laissez macérer 10-15 minutes.\r\n2.Retirez la tarte du réfrigérateur et garnissez de fraises macérées. Servez.', 3, 'https://www.anasbakingchronicles.com/wp-content/uploads/2022/07/Tarte-aux-fraises-featured-image-1.jpg', '2024-07-17 13:20:57', 1),
(2, 'carot soup', '6 carottes (600 g), coupées en rondelles minces\r\n1 oignon (200 g), haché finement\r\n1 gousse d\'ail, hachée finement\r\n1 c. à soupe de beurre non salé (14 g)\r\n3 1/2 c. à thé de poudre de curry (10 g)\r\n2 tasses de bouillon de poulet (500 mL)\r\n2 3/4 tasses d\'eau (700 mL)\r\n1/2 tasse de crème 15% (125 mL)\r\n1 pincée de sel [optionnel] (0.2 g)\r\nPoivre au goût [optionnel]', '\r\n1.Tranchez les carottes en rondelles et hachez finement l\'oignon et l\'ail.\r\n2.Faites suer l\'oignon et l\'ail dans le beurre, puis ajoutez les carottes et faites-les sauter.\r\n3.Ajoutez la poudre de curry, salez et poivrez, puis versez le bouillon et l\'eau.\r\n4.Laissez mijoter à couvert pendant environ 20 minutes jusqu\'à ce que les carottes soient tendres.\r\n5.Réduisez la soupe en purée, ajoutez la crème, chauffez encore quelques minutes et ajustez l\'assaisonnement avant de servir.', 1, 'https://cdn.pratico-pratiques.com/app/uploads/sites/4/2018/08/30171704/potage-carottes-et-panais.jpeg', '2024-07-17 13:20:57', 1),
(3, 'Pancakes', 'Farine tout usage-500 ml (2 tasses)\r\nSel-2,5 ml (½ c. à thé)\r\nPoudre à pâte-10 ml (2 c. à thé)\r\nGros œufs-2\r\nSucre-45 ml (3 c. à soupe)\r\nExtrait de vanille-5 ml (1 c. à thé)\r\nLait-430 ml (1 ¾ tasse)\r\nBeurre pour la cuisson', '1.Mélangez la farine, le sel et la poudre à pâte dans un bol; réservez.\r\n2.Dans un autre bol, battez les œufs, le sucre et la vanille avec un batteur électrique pendant 5 minutes.\r\n3.Ajoutez la moitié du lait au mélange d\'œufs, puis incorporez le mélange de farine. Ajoutez le reste du lait et fouettez jusqu\'à homogénéité.\r\n4.Laissez reposer la pâte 10 minutes à température ambiante.\r\n5.Faites cuire les pancakes dans une poêle chaude et beurrée, en versant environ 85 ml de pâte par pancake, jusqu’à ce que les deux côtés soient dorés.', 3, 'https://www.inspiredtaste.net/wp-content/uploads/2016/07/Pancake-Recipe-1-1200.jpg', '2024-07-17 13:20:57', 1),
(4, 'Banana Bread', '2 tasses (250 g) de farine tout usage\r\n1 cuillère à café de bicarbonate de soude\r\n1/4 cuillère à café de sel\r\n1/2 cuillère à café de cannelle moulue\r\n1/2 tasse (113 g) de beurre non salé, ramolli\r\n3/4 tasse (150 g) de sucre brun, tassé\r\n2 gros œufs, à température ambiante\r\n1/3 tasse (80 g) de yaourt nature ou de crème aigre, à température ambiante\r\n2 tasses (460 g) de bananes écrasées (environ 4 grandes bananes mûres)\r\n1 cuillère à café d\'extrait de vanille\r\n(Optionnel) 3/4 tasse (100 g) de noix de pécan ou de noix hachées', '\r\n1.Préchauffez le four à 350°F (177°C) et graissez un moule à pain de 9x5 pouces.\r\n2.Mélangez la farine, le bicarbonate de soude, le sel et la cannelle.\r\n3.Battez le beurre et le sucre jusqu\'à obtenir une texture crémeuse, puis ajoutez les œufs, le yaourt, les bananes et la vanille.\r\n4.Incorporez les ingrédients secs sans trop mélanger, puis ajoutez les noix si désiré.\r\n5.Versez dans le moule et faites cuire 60-65 minutes, en couvrant de papier aluminium à mi-cuisson. Laissez refroidir avant de trancher et de servir. Conservez à température ambiante pendant 2 jours ou au réfrigérateur jusqu\'à 1 semaine.', 3, 'https://www.inspiredtaste.net/wp-content/uploads/2016/12/Easy-Banana-Bread-Recipe-1-1200.jpg', '2024-07-17 13:20:57', 1),
(5, 'Brownies', '115 g (3/4 tasse) de farine tout usage non blanchie\r\n25 g (1/4 tasse) de cacao, tamisé\r\n1 ml (1/4 c. à thé) de sel\r\n170 g (6 oz) de chocolat noir, haché\r\n170 g (3/4 tasse) de beurre non salé, coupé en cubes\r\n210 g (1 tasse) de sucre\r\n5 ml (1 c. à thé) d\'extrait de vanille\r\n3 oeufs', '1.Placer la grille dans le centre du four. Préchauffer le four à 165 °C (325 °F). Beurrer un moule carré de 20 cm (8 po) et le tapisser d\'une bande de papier parchemin en la laissant dépasser sur deux côtés.\r\n2.Dans un bol, mélanger la farine, le cacao et le sel.\r\n3.Dans un bol, au-dessus d\'un bain-marie, fondre le chocolat et le beurre. Retirer le bol du bain-marie. Incorporer le sucre et la vanille au fouet. Ajouter les oeufs, un à la fois, et fouetter 2 minutes. Incorporer délicatement les ingrédients secs. Répartir la pâte dans le moule.\r\n4.Cuire au four de 30 à 35 minutes ou jusqu\'à ce qu\'un cure-dents inséré au centre du brownies en ressorte avec quelques grumeaux et non pas complètement propre. Laisser refroidir dans le moule de 2 à 3 heures. Démouler et couper en carrés.', 3, 'https://cdn.loveandlemons.com/wp-content/uploads/2020/01/recipe-for-brownies-1.jpg', '2024-07-17 13:20:57', 1),
(6, 'Cookies', 'Oeuf 1\r\nSucre 85 g\r\nBeurre doux 85 g\r\nFarine 150 g\r\nPépites de chocolat 100 g\r\nSucre vanillé 1 sachet\r\nLevure chimique 1 c à c\r\nSel ½ c à c', '1.Ramollir le beurre et le mélanger avec le sucre.\r\n2.Ajouter l\'œuf et éventuellement le sucre vanillé.\r\n3.Incorporer la farine, la levure chimique, le sel et les pépites de chocolat.\r\n4.Former des boules de pâte sur une plaque de cuisson beurrée ou recouverte de silicone.\r\n5.Cuire à 180°C pendant 8 à 10 minutes, jusqu\'à ce que les contours commencent à brunir.', 3, 'https://cdn.loveandlemons.com/wp-content/uploads/2020/02/vegan-chocolate-chip-cookies.jpg', '2024-07-17 13:20:57', 1),
(7, 'Quiche', 'poivre\r\nsel\r\nmuscade\r\n20 cl de crème fraîche\r\n30 g de beurre\r\n200 g de lardons\r\n200 g de pâte brisée\r\n3 oeufs\r\n20 cl de lait ', '1.Préchauffer le four à 180°C. Étaler et piquer la pâte brisée dans un moule, puis parsemer de copeaux de beurre.\r\n2.Rissoler les lardons et les éponger.\r\n3.Battre les œufs, la crème fraîche et le lait, puis ajouter les lardons.\r\n4.Assaisonner avec sel, poivre et muscade.\r\n5.Verser le mélange sur la pâte et cuire 45 à 50 minutes.', 2, 'https://www.cookingclassy.com/wp-content/uploads/2021/03/quiche-3.jpg', '2024-07-17 13:20:57', 1),
(8, 'Chicken Salad', '2 poitrines de poulet grillées, coupées en morceaux\r\n½ tasse d’amandes tranchées\r\n½ petit oignon rouge ou 1 petit échalote, tranché\r\n4 tasses de laitue romaine hachée\r\n4 tasses d’épinards bébé\r\n8 onces de fraises, équeutées et coupées\r\n1 tasse de tomates cerises, coupées en deux\r\n2 avocats mûrs, coupés en dés\r\n⅛ cuillère à café de sel kasher\r\n¾ tasse de fromage feta\r\n\r\nPour la vinaigrette :\r\n\r\n¼ tasse de jus de citron frais\r\n3 cuillères à soupe d’huile d’olive extra-vierge\r\n2 cuillères à soupe de miel\r\n1 cuillère à café de moutarde de Dijon\r\n½ cuillère à café de sel kasher\r\n⅛ cuillère à café de poivre noir', '1.Préparer les amandes : Faites-les griller dans une poêle à feu moyen, puis transférez-les pour les laisser refroidir.\r\n2.Préparer l\'oignon : Faites-le tremper dans de l\'eau froide pour enlever son goût fort.\r\n3.Préparer la vinaigrette : Mélangez le jus de citron, l\'huile d\'olive, le miel, la moutarde, le sel et le poivre.\r\n4.Assembler la salade : Mélangez la laitue romaine, les épinards, les fraises, les tomates, l\'avocat et l\'oignon égoutté dans un grand bol. Ajoutez le poulet et la moitié de la vinaigrette, puis mélangez.\r\n5.Ajouter les garnitures : Incorporez l\'avocat restant, la feta et les amandes. Mélangez délicatement et servez avec le reste de la vinaigrette en accompagnement.', 1, 'https://www.wellplated.com/wp-content/uploads/2023/04/Lemon-Grilled-Chicken-Salad.jpg', '2024-07-17 13:20:57', 1),
(9, 'Lasagna', 'Viande hachée (bœuf ou dinde)\r\nSauce spaghetti (du commerce ou maison)\r\nFromages : cottage cheese, mozzarella, parmesan\r\nŒufs\r\nAssaisonnements : persil séché, sel, poivre noir\r\nNouilles à lasagne\r\nEau', '1.Cuire et égoutter la viande hachée, puis mélanger avec la sauce spaghetti et laisser mijoter.\r\n2.pré-cuire les nouilles à lasagne\r\n3.Mélanger le cottage cheese, 2 tasses de mozzarella, les œufs, la moitié du parmesan et les assaisonnements. \r\n4.placer les nouilles \r\n5.Cuire couvert pendant 45 minutes, puis découvrir et cuire encore 10 minutes.', 2, 'https://www.budgetbytes.com/wp-content/uploads/2022/12/Homemade-Lasagna-V1.jpg', '2024-07-17 13:20:57', 1),
(10, 'Fried rice', '3 cuillères à soupe de beurre (divisées)\r\n2 gros œufs (battus)\r\n2 carottes moyennes (pelées et coupées en dés)\r\n1 petit oignon blanc (coupé en dés)\r\n1/2 tasse de petits pois surgelés\r\n3 gousses d\'ail (hachées)\r\nSel et poivre noir\r\n4 tasses de riz cuit et refroidi (de préférence du riz blanc à grain court)\r\n3 oignons verts (coupés en fines tranches)\r\n3 à 4 cuillères à soupe de sauce soja (ou plus selon le goût)\r\n2 cuillères à café de sauce d\'huître (optionnel)\r\n1/2 cuillère à café d\'huile de sésame grillé', '1.Faire fondre 1/2 cuillère à soupe de beurre dans une grande poêle à feu moyen-élevé. Ajouter les œufs et les brouiller, puis les transférer dans une assiette.\r\n2.Ajouter 1 cuillère à soupe de beurre dans la poêle et faire fondre. Ajouter les carottes, l\'oignon, les petits pois et l\'ail. Assaisonner avec du sel et du poivre. Faire sauter pendant environ 5 minutes jusqu\'à ce que les carottes et l\'oignon soient tendres.\r\n3.Augmenter le feu à élevé, ajouter le reste du beurre (1 1/2 cuillère à soupe) et faire fondre. Ajouter immédiatement le riz, les oignons verts, la sauce soja et la sauce d\'huître (si utilisée), puis mélanger. Faire sauter pendant environ 3 minutes, en remuant de temps en temps.\r\n4.Ajouter les œufs brouillés et mélanger. Retirer du feu et ajouter l\'huile de sésame. Goûter et ajuster l\'assaisonnement avec plus de sauce soja si nécessaire.\r\n5.Servir immédiatement ou réfrigérer dans un récipient hermétique jusqu\'à 3 jours.', 2, 'https://www.gimmesomeoven.com/wp-content/uploads/2017/07/How-To-Make-Fried-Rice-Recipe-2-1.jpg', '2024-07-17 13:20:57', 1),
(11, 'Salmon', '4 filets de saumon (180g chacun), sans peau et sans arêtes\r\n1/2 cuillère à café de sel\r\n1/4 cuillère à café de poivre noir\r\n1 1/2 cuillères à soupe d\'huile d\'olive\r\n1 cuillère à soupe d\'ail (environ 2 gousses), finement haché à la main (ne pas utiliser de presse-ail)\r\n90g de beurre salé (ou non salé + 1/4 cuillère à café de sel), coupé en cubes\r\n1 cuillère à café de jus de citron (plus au goût)\r\n2 cuillères à café de persil, finement haché\r\n', '1.Préparer le saumon : Sortir le saumon du réfrigérateur 30 minutes avant la cuisson. Saupoudrer les deux côtés de sel et de poivre.\r\n2.Saisir le saumon pendant 3 minutes : Chauffer l\'huile dans une grande poêle antiadhésive à feu moyen-élevé. Ajouter le saumon, côté présentation (côté incurvé) vers le bas, et cuire pendant 3 minutes jusqu\'à ce qu\'il soit doré.\r\n3.Retourner et cuire 1 minute, puis ajouter le beurre : Retourner le saumon et cuire l\'autre côté pendant 1 minute. Ajouter ensuite le beurre.\r\n4.Arroser pendant 1 1/2 minute : Une fois le beurre fondu et mousseux, ajouter l\'ail et commencer immédiatement à arroser le saumon avec le beurre bouillonnant pendant 1 1/2 minute. Pour ce faire, incliner légèrement la poêle pour que le beurre se rassemble d\'un côté. Utiliser une grande cuillère pour recueillir le beurre et l\'arroser sur le saumon.\r\n5.Retirer le saumon du feu : Vérifier la température interne du saumon. Elle doit être de 50°C pour une cuisson mi-saignante (optimal pour la jutosité). Transférer le saumon dans une assiette et laisser reposer pendant 3 minutes – la température montera à 53°C.\r\n6.Ajouter le jus de citron au beurre : Remettre la poêle sur le feu éteint pour garder le beurre chaud. Ajouter le jus de citron.', 2, 'https://www.southernliving.com/thmb/TEVzapcH5QEwkE4wDXYHUe1IKmU=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Pan_Seared_Salmon_009-f6a7a1181726444c84167e322ca45bf7.jpg', '2024-07-17 13:20:57', 1),
(12, 'Beef burger', '1 gros œuf\r\n1/2 cuillère à café de sel\r\n1/2 cuillère à café de poivre noir moulu\r\n1 livre de bœuf haché\r\n1/2 tasse de chapelure fine et sèche', '1.Préparation du mélange : Dans un bol moyen, fouetter ensemble l\'œuf, le sel et le poivre. Ajouter le bœuf haché et la chapelure, puis mélanger avec les mains ou une fourchette jusqu\'à obtention d\'un mélange homogène.\r\n2.Formation des galettes : Former quatre galettes de 3/4 pouces d\'épaisseur.\r\n3.Cuisson des galettes : Placer les galettes sur un grill préchauffé ou dans une poêle\r\n4.Couvrir et cuire pendant 6 à 8 minutes de chaque côté, ou jusqu\'à la cuisson désirée. La température interne doit atteindre au moins 70°C.', 2, 'https://www.allrecipes.com/thmb/5bbowF39Flo1sblOqjMQifuj1a8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/25473-the-perfect-basic-burger-DDMFS-4x3-56eaba3833fd4a26a82755bcd0be0c54.jpg', '2024-07-17 13:20:57', 1),
(13, 'Spaghetti bolognese', '1 oignon, finement haché\r\n2 gousses d\'ail, hachées\r\n1 livre de bœuf haché (85-90% maigre)\r\n28 oz de tomates concassées\r\n2 cuillères à soupe de concentré de tomate\r\n1/2 cuillère à café de sel\r\n1/4 cuillère à café de poivre noir\r\n1 cuillère à soupe de basilic séché\r\n1/4 cuillère à café de flocons de piment rouge\r\n1 croûte de parmesan\r\n10 oz de spaghetti non cuits\r\n2 cuillères à soupe d\'huile d\'olive', '1.Cuisson de l\'oignon et de l\'ail : Préchauffer une grande poêle à feu moyen/élevé et ajouter 2 cuillères à soupe d\'huile d\'olive. Ajouter l\'oignon haché et cuire environ 10 minutes jusqu\'à ce qu\'il soit tendre et commence à caraméliser. Ajouter l\'ail et cuire 30 secondes.\r\n2.Cuisson du bœuf : Ajouter le bœuf haché et le décomposer en petits morceaux. Cuire environ 10 minutes jusqu\'à ce qu\'il soit bien cuit.\r\n3.Préparation de la sauce : Ajouter les tomates concassées, le concentré de tomate, le sel, le poivre, le basilic séché et les flocons de piment rouge. Mélanger et ajouter la croûte de parmesan. Laisser mijoter à feu doux pendant environ 20 minutes en remuant de temps en temps.\r\n4.Cuisson des pâtes : Pendant que la sauce mijote, faire bouillir une grande casserole d\'eau salée et cuire les spaghetti selon les instructions jusqu\'à ce qu\'ils soient al dente. Égoutter les pâtes en réservant 1 tasse d\'eau de cuisson.\r\n5.Assemblage : Ajouter les spaghetti égouttés à la sauce et bien mélanger. Si la sauce est trop épaisse, ajouter quelques cuillères d\'eau de cuisson réservée. Saupoudrer de parmesan râpé et de persil haché avant de servir.', 2, 'https://veronikaskitchen.com/wp-content/uploads/2021/01/20201230-7D8A0130.webp', '2024-07-17 13:20:57', 1),
(14, 'Caeser salad', 'Pour les croûtons :\r\n\r\n1/2 baguette française, coupée en tranches fines (1/4\" d\'épaisseur)\r\n3 cuillères à soupe d\'huile d\'olive extra vierge\r\n1 cuillère à café d\'ail émincé (2 petites gousses)\r\n2 cuillères à soupe de parmesan râpé\r\n\r\nPour la vinaigrette César :\r\n\r\n2 petites gousses d\'ail, émincées (1 cuillère à café)\r\n2 cuillères à café de moutarde de Dijon\r\n1 cuillère à café de sauce Worcestershire\r\n2 cuillères à café de jus de citron frais\r\n1 1/2 cuillère à café de vinaigre de vin rouge\r\n1/3 tasse d\'huile d\'olive extra vierge\r\n1/2 cuillère à café de sel de mer, ou au goût\r\n1/8 cuillère à café de poivre noir, plus au goût\r\n\r\nPour la salade César :\r\n\r\n1 grande laitue romaine (ou 2 petites têtes de romaine)\r\n1/3 tasse de parmesan râpé ou en copeaux', 'Préparation des croûtons :\r\n\r\n1.Préchauffer le four à 350˚F.\r\nCouper la baguette en deux dans le sens de la longueur, puis en tranches diagonales de 1/4\" d\'épaisseur. Placer les tranches de pain sur une plaque de cuisson.\r\n2.Dans un petit bol, mélanger 3 cuillères à soupe d\'huile d\'olive et 1 cuillère à café d\'ail haché. Verser l\'huile à l\'ail sur les croûtons et saupoudrer de 2 cuillères à soupe de parmesan râpé. Mélanger jusqu\'à ce que les croûtons soient bien enrobés.\r\n3.Étaler les croûtons en une seule couche sur la plaque de cuisson et cuire au four à 350˚F jusqu\'à ce qu\'ils soient légèrement dorés et croustillants (10-12 minutes).\r\n\r\nPréparation de la vinaigrette César :\r\n\r\n4.Dans un petit bol, fouetter ensemble l\'ail, la moutarde de Dijon, la sauce Worcestershire, le jus de citron et le vinaigre de vin rouge.\r\n5.Ajouter lentement l\'huile d\'olive en fouettant constamment.\r\n6.Ajouter le sel et le poivre et fouetter jusqu\'à ce que la vinaigrette soit bien mélangée.\r\n\r\nPréparation de la salade César :\r\n\r\n7.Rincer, sécher et couper ou déchirer la laitue romaine en morceaux de la taille d\'une bouchée. Placer dans un grand bol de service.\r\n8.Saupoudrer généreusement de parmesan râpé et ajouter les croûtons refroidis.\r\n9.Verser la vinaigrette César et mélanger délicatement jusqu\'à ce que la laitue soit uniformément enrobée. Servir immédiatement.', 1, 'https://natashaskitchen.com/wp-content/uploads/2019/01/Caesar-Salad-Recipe-3.jpg', '2024-07-17 13:20:57', 1),
(15, 'Club Sandwich', 'Tomate (en saison)\r\n3 tranches de pain de mie anglais\r\n1 escalope de poulet ou de dinde extra fine\r\n2 tranches de bacon\r\n0.5 avocat\r\n1 œuf dur\r\nFeuilles de salade (laitue, batavia ou iceberg)\r\n1 cuillère à soupe de mayonnaise', '1.Cuisson : Cuire l\'escalope à feu doux et faire frire les tranches de bacon.\r\n2.Toaster le pain : Faire légèrement griller les tranches de pain de mie.\r\n3.Assemblage :\r\n  -Sur la première tranche, étaler un peu de mayonnaise, ajouter de la salade, l\'escalope découpée en fines lamelles, quelques rondelles d\'avocat, saler et poivrer légèrement.\r\n  -Recouvrir avec la deuxième tranche de pain de mie, étaler de la mayonnaise, ajouter les rondelles de tomates, d\'œuf dur et le bacon.\r\n  -Recouvrir avec la troisième tranche de pain de mie.\r\n4.Finalisation : Presser avec la paume de la main, maintenir avec 2 cure-dents et couper en deux en diagonale.', 2, 'https://cdn-abioh.nitrocdn.com/iRwsMXPEdaMSNBlSqLBkXmjSJwoqRrps/assets/images/optimized/rev-01bf621/www.apinchofhealthy.com/wp-content/uploads/2018/07/club-sandwich-overhead.jpg', '2024-07-02 13:20:57', 1);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `recettes`
--
ALTER TABLE `recettes`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `recettes`
--
ALTER TABLE `recettes`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=38;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
